title: John Franey # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Graduate Researcher at the Jackson School of Geosciences at the University of Texas at Austin | Gulf Coast Carbon Center
  <br><br>
  Pursuing a Masters Degree in Geophysics with focus on Carbon Capture and Storage.
  <br><br>
  <a href="https://www.linkedin.com/in/john-franey-455076192/">View My LinkedIn Profile</a>
  <br><br>
  <a href="mailto:johnfraney@utexas.edu">johnfraney@utexas.edu</a>
  <br><br>
  <a href="https://franathan.github.io/pdf/Franey_Resume_2021.pdf">Resume</a>
  <br><br>
theme: jekyll-theme-steve
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
